"""Initial database schema

Revision ID: 3236ce93f379
Revises: None
Create Date: 2026-07-23 23:05:42.064254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3236ce93f379'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('rss_url', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sources_id'), 'news_sources', ['id'], unique=False)
    op.create_table('news',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sentiment IN ('positive', 'negative')", name='chk_news_sentiment'),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_news_published', 'news', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index('idx_news_sentiment', 'news', ['sentiment'], unique=False)
    op.create_index('idx_news_slug', 'news', ['slug'], unique=False)
    op.create_index('idx_news_source', 'news', ['source_id'], unique=False)
    op.create_index('idx_news_url', 'news', ['url'], unique=False)
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_news', sa.Integer(), nullable=False),
    sa.Column('success_news', sa.Integer(), nullable=False),
    sa.Column('failed_news', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_logs_id'), 'scrape_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_logs_id'), table_name='scrape_logs')
    op.drop_table('scrape_logs')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_index('idx_news_url', table_name='news')
    op.drop_index('idx_news_source', table_name='news')
    op.drop_index('idx_news_slug', table_name='news')
    op.drop_index('idx_news_sentiment', table_name='news')
    op.drop_index('idx_news_published', table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_news_sources_id'), table_name='news_sources')
    op.drop_table('news_sources')
    # ### end Alembic commands ###
